a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número?', a.isnumeric())
print('É alfanumérico?' , a.isalnum())
print('É alfabético?' , a.isalpha())
print('Está em maiúsculo?' , a.isupper())
print('Está em minúsculo?' , a.islower())
print('Está capitalizado?' , a.istitle())