nome = str(input('Digite seu nome completo: ')).strip()
print(f'Seu nome com todas as letras minúsculas fica:{nome.lower()}')
print(f'Seu nome com todas as letras maiúsculas fica: {nome.upper()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")} letras')
#print(f"Seu primeiro nome tem {nome.find(' ')} letras")
separa = nome.split()
print(f"Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras")